### ISSUE TITLE
JwtAccessTokenConverter will change the refreshToken even when reuseRefreshToken set to true

### ISSUE THREAD

**Issue by bwangfdu** [spring-projects/spring-security-oauth#1193]
I find that the JwtAccessTokenConverter will change the refreshToken when reuseRefreshToken set to true. It happens on the line 247:
 DefaultOAuth2RefreshToken token = new DefaultOAuth2RefreshToken(
					encode(encodedRefreshToken, authentication));
after the encode function is called, the refreshToken was changed (re-encoded). But the DefaultTokenServices will not store the new one cause by Line 178: 
if (!reuseRefreshToken) {
			tokenStore.storeRefreshToken(accessToken.getRefreshToken(), authentication);
		}

To reproduce this case, you can set reuseRefreshToken to true and set the tokenEnhancer to JwtAccessTokenConverter, and after call refresh_token process, there will be no refresh_token can refresh anymore.

**Comment by loesak** [comment]
I can confirm I am having the same issue.

The authorization server returns a new refresh token every time a refresh token is used regardless if "reuseRefreshToken" is set to "true" or not. The refresh token isn't being stored in the TokenStore. This is because the JwtAccessTokenConverter is creating a new refresh token when its "enhance" method is called.

Key Dependencies:
spring-cloud-starter-oauth2:1.2.3.RELEASE
spring-security-oauth2:2.0.15.RELEASE
spring-security-jwt:1.0.9.RELEASE
spring-cloud-starter-security:1.2.3.RELEASE

**Comment by bwangfdu** [comment]
This issue was resolved in later version. It is caused by the order of scopes.

**Comment by bwangfdu** [comment]
I am sorry, the current problem is much different from when I raise this issue two years ago.

**Comment by czeroprime** [comment]
I can confirm this is still an issue also, to expand on what @loesak has said, the method 'JwtAccessTokenConverter.enhance' updates the 'ati' property with the token id('jti' property) from the new access token.

This update to the refresh token is not stored in the database in the 'DefaultTokenServices.refreshAccessToken' method due to the if statement 'if (!this.reuseRefreshToken) {' on line 123.

As the token does in fact change, should the if statement 'if (!this.reuseRefreshToken) {' be removed to fix this issue? And if so the if statement 'if (!this.reuseRefreshToken) {' on line 116 should be removed as this will remove the existing refresh token.

As @dfcoffin pointed out in issue #1109 the spec does in fact say that a new refresh token can be returned on refresh. In a sense we are reusing the existing refresh token as the expiry is not changing, which is not true in the other scenario where a completely new refresh token and updated expiry is generated.

**Comment by czeroprime** [comment]
I have created a PR with a fix for this issue: https://github.com/spring-projects/spring-security-oauth/pull/1668

In the mean time I am excluding the dependency, and using jitpack to use my fix as a dependency instead.

**Comment by jgrandja** [comment]
This is a duplicate of #1109. Please see [comment](https://github.com/spring-projects/spring-security-oauth/issues/1109#issuecomment-546453794)
