### ISSUE TITLE
JwkSetConverter should only accept public key use sig

### ISSUE THREAD

**Issue by erichunterhawthorne** [spring-projects/spring-security-oauth#1871]
Re-opening this as an issue. I'm running into this, as well with tokens created from Microsoft Azure. Failing against spec is not correct behavior.

_Originally posted by @sjoerd-michels in https://github.com/spring-projects/spring-security-oauth/pull/1348/files/b30dbe01e36082cc79d1e3e2e3e4cd896fef2d79_: 
This should not have been closed: the implementation does not follow the spec, so this is a bug.
Now, for example, Spring security does not work with the following JWK key set that is perfectly valid but that does not specify a use attribute:
`{ "keys": [
    { "kty": "RSA",
      "x5t#S256": "...",
      "e": "...",
      "x5t": "...",
      "kid": "SIGNING_KEY",
      "x5c": [
        "...",
        "..."
      ],
      "key_ops": [
        "encrypt",
        "verify"
      ],
      "alg": "RS256",
      "n": "..."
    }
  ]
}`
And unfortunately, it seems impossible to adapt the `JwkSetConverter`.
This should be re-opened / re-considered.

**Comment by jgrandja** [comment]
Thanks for re-opening @erichunterhawthorne. The fix in #1470 should have been more lenient.

I just pushed a fix that excludes JWK's that are NOT `use: sig`.

**Comment by gubespam** [comment]
The initial issue described above has still not been fixed. When a key only has a "key_ops" attribute but no "use" attribute (like the one given in the initial issue description), then Spring skips over that key and acts like the key does not exist.

This is in part due to 

    // gh-1082 - skip arrays such as x5c as we can't deal with them yet
    if (parser.nextToken() == JsonToken.START_ARRAY) {

which skips the key_ops attribute.

Then later only the "use" attribute is examined, not the "key_ops" attribute.

    JwkDefinition.PublicKeyUse publicKeyUse =
        JwkDefinition.PublicKeyUse.fromValue(attributes.get(PUBLIC_KEY_USE));
    if (!JwkDefinition.PublicKeyUse.SIG.equals(publicKeyUse)) {
        continue;
    }

I think the correct behavior is for Spring to examine the values in key_ops when "use" is not present. Note that these two attributes have a different set of expected values. See pages 6 and 7 of the spec [here](https://tools.ietf.org/html/rfc7517#page-6).
